apiVersion: v1
kind: Service
metadata:
  name: mkrew-frontend
  namespace: default
  labels:
    app: mkrew-frontend
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4321
    protocol: TCP
    name: http
  selector:
    app: mkrew-frontend
    tier: frontend
