---
# Service Account dla backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mkrew-backend-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: mkrew-backend@mkrew-478317.iam.gserviceaccount.com

---
# Role pozwalająca na tworzenie i aktualizację Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]

---
# RoleBinding łączący ServiceAccount z Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mkrew-backend-secret-manager
  namespace: default
subjects:
- kind: ServiceAccount
  name: mkrew-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io